[package]
name = "plugin-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "play-plugin"
path = "src/main.rs"

[dependencies]
plugin-core = { path = "../core" }
plugin-overlay = { path = "../overlay" }
plugin-server = { path = "../server" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
ureq = "2"
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security_Cryptography",
    "Win32_Security_WinTrust",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Kernel",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_Storage_FileSystem",
    "Win32_UI_HiDpi",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }