[package]
name = "plugin-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_System_Threading",
] }
anyhow = { workspace = true }

[dependencies.ffmpeg-next]
version = "9"
optional = true

[features]
default = ["ffmpeg"]
ffmpeg = ["dep:ffmpeg-next"]
